-- Seed data: program_studi (15 records from prodi_data.csv)
-- Import example:
--   mysql -u <user> -p <db_name> < application/dbschema/prodi_data.sql

INSERT INTO `program_studi`
  (
    `kode`,
    `nama_prodi`,
    `fakultas`,
    `ketua_prodi`,
    `sekretaris_prodi`,
    `akreditasi`,
    `tgl_berlaku_akreditasi`,
    `tgl_berakhir_akreditasi`,
    `no_sk`,
    `keterangan`,
    `created_at`
  )
VALUES
  (
    '63413',
    'D3-Administrasi Keuangan',
    'Fakultas Ekonomi dan Bisnis',
    'Dr. Hendra Wijaya, S.E., M.Ak.',
    'Rina Kartika, S.E., M.M.',
    'Unggul',
    '2023-08-15',
    '2028-08-14',
    '1234/SK/BAN-PT/Ak-PPJ/Dipl-III/VIII/2023',
    'Program studi administrasi keuangan dengan fokus pada pengelolaan keuangan perusahaan dan lembaga.',
    NOW()
  ),
  (
    '13461',
    'D3-Administrasi Rumah Sakit',
    'Fakultas Ilmu Kesehatan',
    'Dr. Siti Aminah, S.K.M., M.Kes.',
    'Andi Pratama, S.K.M., M.M.',
    'Belum Terakreditasi',
    NULL,
    NULL,
    NULL,
    'Program studi administrasi rumah sakit yang mempersiapkan tenaga ahli manajemen kesehatan.',
    NOW()
  ),
  (
    '13453',
    'D3-Analis Kesehatan',
    'Fakultas Ilmu Kesehatan',
    'Dr. Dewi Susanti, S.Si., M.Biomed.',
    'Budi Hartono, S.Si., M.Si.',
    'B',
    '2022-05-20',
    '2027-05-19',
    '2345/SK/BAN-PT/Ak-PPJ/Dipl-III/V/2022',
    'Program studi analis kesehatan dengan keahlian laboratorium klinik dan diagnostik.',
    NOW()
  ),
  (
    '61316',
    'D4-Bisnis Digital',
    'Fakultas Ekonomi dan Bisnis',
    'Dr. Anita Rahman, S.E., M.M.',
    'Bambang Sutrisno, S.E., M.M.',
    'Baik',
    '2024-02-10',
    '2029-02-09',
    '3456/SK/BAN-PT/Ak-PPJ/Dipl-IV/II/2024',
    'Program studi sarjana terapan bisnis digital dengan fokus startup dan e-commerce.',
    NOW()
  ),
  (
    '48401',
    'D3-Farmasi',
    'Fakultas Ilmu Kesehatan',
    'apt. Dr. Maya Puspita, S.Farm., M.Farm.',
    'apt. Rizki Andini, S.Farm., M.Farm.',
    'C',
    '2021-09-15',
    '2026-09-14',
    '4567/SK/BAN-PT/Ak-PPJ/Dipl-III/IX/2021',
    'Program studi farmasi yang menghasilkan tenaga asisten apoteker profesional.',
    NOW()
  ),
  (
    '11401',
    'D3-Fisioterapi',
    'Fakultas Ilmu Kesehatan',
    'Dr. Ahmad Fauzan, S.Ft., M.Fis.',
    'Indah Permata, S.Ft., M.Kes.',
    'C',
    '2021-11-01',
    '2026-10-31',
    '5678/SK/BAN-PT/Ak-PPJ/Dipl-III/XI/2021',
    'Program studi fisioterapi dengan keahlian rehabilitasi medik dan terapi fisik.',
    NOW()
  ),
  (
    '57302',
    'D4-Komputerisasi Akuntansi',
    'Fakultas Teknik dan Ilmu Komputer',
    'Dr. Hadi Santoso, S.E., S.Kom., M.Kom.',
    'Lina Marlina, S.Kom., M.Ak.',
    'Baik Sekali',
    '2023-06-25',
    '2028-06-24',
    '6789/SK/BAN-PT/Ak-PPJ/Dipl-IV/VI/2023',
    'Program studi sarjana terapan yang menggabungkan akuntansi dan teknologi informasi.',
    NOW()
  ),
  (
    '13363',
    'D4-Manajemen Informasi Kesehatan',
    'Fakultas Ilmu Kesehatan',
    'Dr. Ratna Wijayanti, S.K.M., M.K.M.',
    'Dian Purnama, S.K.M., M.Kes.',
    'Baik',
    '2024-01-20',
    '2029-01-19',
    '7890/SK/BAN-PT/Ak-PPJ/Dipl-IV/I/2024',
    'Program studi manajemen informasi kesehatan dengan fokus rekam medis elektronik.',
    NOW()
  ),
  (
    '57301',
    'D4-Manajemen Informatika',
    'Fakultas Teknik dan Ilmu Komputer',
    'Dr. Ir. Budi Santoso, S.Kom., M.Kom.',
    'Dewi Anggraini, S.Kom., M.T.',
    'Baik Sekali',
    '2023-09-10',
    '2028-09-09',
    '8901/SK/BAN-PT/Ak-PPJ/Dipl-IV/IX/2023',
    'Program studi sarjana terapan manajemen informatika dengan keunggulan sistem enterprise.',
    NOW()
  ),
  (
    '57401',
    'D3-Manajemen Informatika',
    'Fakultas Teknik dan Ilmu Komputer',
    'Ir. Farhan Abdullah, S.Kom., M.T.',
    'Nurul Hidayah, S.Kom., M.Kom.',
    'Baik Sekali',
    '2023-07-01',
    '2028-06-30',
    '9012/SK/BAN-PT/Ak-PPJ/Dipl-III/VII/2023',
    'Program studi manajemen informatika dengan keahlian pengembangan aplikasi dan database.',
    NOW()
  ),
  (
    '13461-MPRS',
    'D3-Manajemen Pelayanan Rumah Sakit',
    'Fakultas Ilmu Kesehatan',
    'Dr. Kartini Wulandari, S.K.M., M.M.',
    'Agus Setiawan, S.K.M., M.Kes.',
    'Baik Sekali',
    '2023-03-15',
    '2028-03-14',
    '0123/SK/BAN-PT/Ak-PPJ/Dipl-III/III/2023',
    'Program studi manajemen pelayanan rumah sakit dengan fokus mutu layanan kesehatan.',
    NOW()
  ),
  (
    '90347',
    'D4-Produksi Media',
    'Fakultas Teknik dan Ilmu Komputer',
    'Dr. Rizky Pratama, S.Sn., M.Ds.',
    'Eka Putri, S.Ds., M.Sn.',
    'Belum Terakreditasi',
    '2025-01-10',
    '2026-01-09',
    '1122/SK/BAN-PT/Akred-S/Dipl-IV/I/2025',
    'Program studi sarjana terapan produksi media dengan keahlian multimedia dan broadcasting.',
    NOW()
  ),
  (
    '13462',
    'D3-Rekam Medik Dan Informasi Kesehatan',
    'Fakultas Ilmu Kesehatan',
    'Dr. Sri Wahyuni, S.K.M., M.Kes.',
    'Joko Susilo, A.Md.RMIK., S.K.M.',
    'A',
    '2022-04-20',
    '2027-04-19',
    '2233/SK/BAN-PT/Ak-PPJ/Dipl-III/IV/2022',
    'Program studi rekam medik dan informasi kesehatan dengan standar kompetensi nasional.',
    NOW()
  ),
  (
    '56401',
    'D3-Teknik Komputer',
    'Fakultas Teknik dan Ilmu Komputer',
    'Dr. Eng. Wahyu Hidayat, S.T., M.T.',
    'Linda Permata, S.T., M.Kom.',
    'B',
    '2022-08-15',
    '2027-08-14',
    '3344/SK/BAN-PT/Ak-PPJ/Dipl-III/VIII/2022',
    'Program studi teknik komputer dengan keahlian jaringan komputer dan IoT.',
    NOW()
  ),
  (
    '13450',
    'D3-Teknologi Laboratorium Medis',
    'Fakultas Ilmu Kesehatan',
    'Dr. Endang Susilowati, S.Si., M.Biomed.',
    'Ari Wibowo, S.Si., M.Si.',
    'Belum Terakreditasi',
    NULL,
    NULL,
    NULL,
    'Program studi teknologi laboratorium medis dengan fokus diagnostik dan penelitian klinis.',
    NOW()
  );
